config/routes.rb
Rails.application.routes.draw do

  mount Chat::Engine => "/chat", as: "chat"
  devise_for :users, :controllers => { registrations: 'registrations' }
  root 'home#index'
  get "/about", :controller => "home", :action => "about"
  get "/load_active", :controller => "home", :action => "load_active"
  get "/load_available", :controller => "home", :action => "load_available"
  resources :games do
    patch :forfeit
  end
  resources :pieces , only: :update
  resources :users, only: :show

  post 'games/:game_id/:piece_id/:x_position/:y_position', :to => 'games#move', :as => 'move'
  get 'games/:game_id/promote/:piece_id/:x_position/:y_position', :to => 'games#promote', :as => 'promote'
  post 'games/:game_id/promoted/:old_id/:new_id/:x_position/:y_position', :to => 'games#promoted', :as => 'promoted'

  get 'games/:game_id/load_board', :controller => "games", :action => "load_board"
  get 'games/:game_id/load_display', :controller => "games", :action => "load_display"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @games = Game.all
    @current_user = current_user
  end

  def about
  end

  def load_active
    @games = Game.all

    respond_to do |format|
      format.js
    end

  end

  def load_available
    @games = Game.all
    @current_user = current_user

    respond_to do |format|
      format.js
    end

  end
  
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/views/home/_active.html.erb
<% @games.active.each do |game| %>
    <div class="booyah-box col-10 offset-1">
      <h1><%= game.name %></h1>
      <% if game.user.present? %>
        <small><%= game.user.email %></small>
      <% end %>
      <%= simple_form_for game, :url => game_path(game.id), :method => :get do |f| %>
        <%= f.submit 'Play', class: 'btn btn-danger' %>
      <% end %>
   </div>
  <% end %>

app/views/home/_available.html.erb
<% @games.available.each do |game| %>
    <div class="booyah-box col-10 offset-1">
        <h1><%= game.name %></h1>
        <% if game.user.present? %>
          <small><%= game.user.email %></small>
        <% end %>
        <%= simple_form_for game do |f| %>
          <% if game.user.present? %>
              <% if game.user.id != @current_user.id %>
                  <%= f.submit 'Join', class: 'btn btn-danger' %>
              <% end %>
          <% end %>
        <% end %>
      </div>
    <% end %>
  <br />
</div>

app/views/home/about.html.erb
<br /> 
  <div class="booyah-box col-10 offset-1">
    <br />
    <h1 class="text-center" id='about-header'>About Chess App</h1>
    <br />
    <p class="about-intro text-center">
      Chess App is a fully functional chess application created by Team MovingOnUp! for <a target="_blank" href="https://professionaled.utexas.edu/online-coding-boot-camp-certificate-program/">The UT Austin Online Boot Camp's</a> full-stack development curriculum by these MovingOnUp! developers:
    </p>
    <br />

    <div class="row feature">
      <div class="col-12 col-sm">
        <%= image_tag 'chrish.jpg', class: 'img-fluid about-image' %>
        <br />
        <p class="about-names">Chris Howle</p>
        <p>
        Chris is an aspiring full stack developer with an emphasis on Ruby on Rails and Angular. With a Masters in Computer Engineering and Computer Science, most of his career has focused on system administration and data analytics.</p>
        <div class="text-center">
          <%= link_to 'https://github.com/cthowl01' do %>
          <span class="fa fa-github-square fa-2x social-button"></span>
          <% end %>
          <%= link_to 'https://www.linkedin.com/in/chrishowle/' do %>
          <span class="fa fa-linkedin-square fa-2x social-button"></span>
          <% end %>
        </div>
        <br />
        <br />
      </div>

      <div class="col-12 col-sm">
        <%= image_tag 'carrianel.png', class: 'img-fluid about-image' %>
        <br />
        <p class="about-names">Carriane Linzer</p>
        <p>
          Carriane is an aspiring web developer with an emphasis on Ruby on Rails. Most of her career has focused on working with people with developmental disabilities. Carriane describes herself as a lover of languages, animal lover, and a lover of knowledge. </p>
        <div class="text-center">
          <%= link_to 'http://github.com/Yonttee' do %>
          <span class="fa fa-github-square fa-2x social-button"></span>
          <% end %>
        </div>
        <br />
        <br />
      </div>

      <div class="col-12 col-sm">
        <%= image_tag 'jacquesw.jpg', class: 'img-fluid about-image' %>
        <br />
        <p class="about-names">Jacques Wooldridge</p>
        <p>
        Jacques is an aspiring full stack developer with an emphasis on Ruby on Rails and React, that has a passion for making system interaction as intuitive and robust as possible. A former Mainframe application developer with a desire make financial systems user friendly and intuitive. He loves being with his family and being outdoors, fishing and hunting. </p>
        <div class="text-center">
          <%= link_to 'http://github.com/j1wooldridge' do %>
          <span class="fa fa-github-square fa-2x social-button"></span>
          <% end %>
          <%= link_to 'www.linkedin.com/in/jacques-wooldridge-0b754410/' do %>
          <span class="fa fa-linkedin-square fa-2x social-button"></span>
          <% end %>
        </div>
        <br />
        <br />
      </div>

      <div class="col-12 col-sm">
        <%= image_tag 'lorin.png', class: 'img-fluid about-image' %>
        <br />
        <p class="about-names">Lorin Jones</p>
        <p>
        Lorin Jones is an engineer with an interest in software developement in backend logic and infrastructure. He enjoys the challenge of learning and developing new skills and continually developing himself into a versatile individual. He enjoys fishing and family time with his beautiful wife and their dogs. </p>
        <div class="text-center">
          <%= link_to 'https://github.com/ljones1877/' do %>
          <span class="fa fa-github-square fa-2x social-button"></span>
          <% end %>
          <%= link_to 'https://www.linkedin.com/in/lorin-jones-8182b163/' do %>
          <span class="fa fa-linkedin-square fa-2x social-button"></span>
          <% end %>
        </div>
        <br />
        <br />
      </div>
    </div>
  </div>

  <div class="booyah-box col-10 offset-1 tools">
    <h5 class="text-center about-tools">Chess App was built utilizing the following languages and tools: </h5>
    <br />
    <div class="icons">
      <%= image_tag 'github.png', class: 'icon' %>
      <%= image_tag 'rubocop.png', class: 'icon' %>
      <%= image_tag 'trello.png', class: 'icon' %>
      <%= image_tag 'slack.png', class: 'icon' %>
      <%= image_tag 's3.png', class: 'icon', size: '150x50' %>
      <%= image_tag 'firebase.png', class: 'icon', size: '150x50' %>

      <br class="clr" />
      <%= image_tag 'skills.png', class: 'icon' %>
    </div>
       <br />
  </div>
<br />

app/views/home/index.html.erb
<div class="background">

  <div class="col-10 offset-1">

  <h1>Hello, <%= User.find_by_id(current_user.id).email %></h1>

  <h2 style="text-align:left">
    <% flash.each do |type, msg| %>
            <%= msg %>
    <% end %>
  </h2>

  <h2>Active games:</h2>

  </div>

  <div id="act">

  <%= render "active", locals: {:games => @games} %>

  </div>

  <div class="col-10 offset-1">

  <h2>Available games:</h2>

  </div>

  <div id="ava">

  <%= render "available", locals: {:games => @games} %>

  </div>

app/views/home/load_active.js.erb
$('#act').fadeOut().html("<%= render "active", locals: {:games => @games} %>").fadeIn(1000);

app/views/home/load_available.js.erb
$('#ava').html("<%= j(render "available", locals: {:games => @games, :user => @user}) %>");