config/routes.rb
Rails.application.routes.draw do

  mount Chat::Engine => "/chat", as: "chat"
  devise_for :users, :controllers => { registrations: 'registrations' }
  root 'home#index'
  get "/about", :controller => "home", :action => "about"
  get "/load_active", :controller => "home", :action => "load_active"
  get "/load_available", :controller => "home", :action => "load_available"
  resources :games do
    patch :forfeit
  end
  resources :pieces , only: :update
  resources :users, only: :show

  post 'games/:game_id/:piece_id/:x_position/:y_position', :to => 'games#move', :as => 'move'
  get 'games/:game_id/promote/:piece_id/:x_position/:y_position', :to => 'games#promote', :as => 'promote'
  post 'games/:game_id/promoted/:old_id/:new_id/:x_position/:y_position', :to => 'games#promoted', :as => 'promoted'

  get 'games/:game_id/load_board', :controller => "games", :action => "load_board"
  get 'games/:game_id/load_display', :controller => "games", :action => "load_display"
end

app/models/game.rb
class Game < ApplicationRecord
  enum result: {black_wins: 0, white_wins: 1, stalemate: 2}
  scope :available, -> { Game.where(white_player_id: [nil, ""]).or(Game.where(black_player_id: [nil, ""])) }
  scope :active, -> { Game.where(current_status: "active") }
  

  belongs_to :user

  has_many :pieces
  has_many :user_games
  has_many :users, through: :user_games
  has_many :messages
  has_many :moves 

  after_create :lay_out_board!

  def contains_piece?(x_position, y_position)
    if pieces.where("(x_position = ? AND y_position = ?)", x_position, y_position).any?
      return true
    else
      return false
    end
  end

  def lay_out_board!
    # WHITE PIECES
      # Pawns
      (1..8).each do |x_position|
        Pawn.create(game_id: id, piece_type: "Pawn", white: true, x_position: x_position, y_position: 7, player_id: white_player_id, name: "Pawn_white")
      end

      # Rooks
      [1, 8].each do |x_position|
        Rook.create(game_id: id, piece_type: "Rook", white: true, x_position: x_position, y_position: 8, player_id: white_player_id, name: "Rook_white")
      end

      # Knights
      [2, 7].each do |x_position|
        Knight.create(game_id: id, piece_type: "Knight", white: true, x_position: x_position, y_position: 8, player_id: white_player_id, name: "Knight_white")
      end

      #Bishops
      [3, 6].each do |x_position|
        Bishop.create(game_id: id, piece_type: "Bishop", white: true, x_position: x_position, y_position: 8, player_id: white_player_id, name: "Bishop_white")
      end

      #King
      King.create(game_id: id, piece_type: "King", white: true, x_position: 5, y_position: 8, player_id: white_player_id, name: "King_white")

      #Queen
      Queen.create(game_id: id, piece_type: "Queen", white: true, x_position: 4, y_position: 8, player_id: white_player_id, name: "Queen_white")

    # BLACK PIECES
      # Pawns
      (1..8).each do |x_position|
        Pawn.create(game_id: id, piece_type: "Pawn", white: false, x_position: x_position, y_position: 2, player_id: black_player_id, name: "Pawn_black")
      end

      # Rooks
      [1, 8].each do |x_position|
        Rook.create(game_id: id, piece_type: "Rook", white: false, x_position: x_position, y_position: 1, player_id: black_player_id, name: "Rook_black")
      end

      # Knights
      [2, 7].each do |x_position|
        Knight.create(game_id: id, piece_type: "Knight", white: false, x_position: x_position, y_position: 1, player_id: black_player_id, name: "Knight_black")
      end

      #Bishops
      [3, 6].each do |x_position|
        Bishop.create(game_id: id, piece_type: "Bishop", white: false, x_position: x_position, y_position: 1, player_id: black_player_id, name: "Bishop_black")
      end

      #King
      King.create(game_id: id, piece_type: "King", white: false, x_position: 5, y_position: 1, player_id: black_player_id, name: "King_black")

      #Queen
      Queen.create(game_id: id, piece_type: "Queen", white: false, x_position: 4, y_position: 1, player_id: black_player_id, name: "Queen_black")
  end

  def white_player
    User.find_by_id(white_player_id)
  end

  def black_player
    User.find_by_id(black_player_id)
  end

  def winner
    User.find_by_id(winner_player_id)
  end

  def loser
    User.find_by_id(loser_player_id)
  end

  def check?
    kings = games.pieces.where(piece_type: "King")
    kings.each do |k|
      game.pieces.where(white: !k.white).each do |piece|
        return true if piece.verify_valid_move(k.x_position, k.y_position)
      end
    end
    false
  end
 
end

app/controllers/games_controller.rb
require "firebase"

class GamesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :show, :move, :update, :forfeit]

    def new
        @game = Game.new
        
    end

    def index
    end
    
    def create
        @game = current_user.games.create(game_params.merge(white_player_id: current_user.id)
        .merge(current_status: "inactive").merge(current_user: current_user.id))

        white_player_email = User.find_by(id: @game.user_id).email
        firebase_id = @game.name
        data = {
            refresh: false
        }
        
        firebase_url    = 'https://fir-chess-270721.firebaseio.com/';
        firebase_secret = '8g8o1V0UsNy7O1I4kcRXlClM8vo4V4Yi44pQOLqt';
        firebase = Firebase::Client.new(firebase_url, firebase_secret)

        path = "games";
        
        response = firebase.push(path, {
            :name => firebase_id,
            :refresh => false,
            :created => Firebase::ServerValue::TIMESTAMP
          })

        puts "Firebase ID is " + response.body["name"];

        @game.update_attributes(firebase_id: response.body["name"]);

        redirect_to root_path
    end


    def update
        @game = Game.find_by_id(params[:id])
        @game.update_attributes(black_player_id: current_user.id.to_i)     
        @pieces = @game.pieces.where(player_id:nil).update_all(player_id: current_user.id)
        @game.update_attributes(turn_player_id: @game.white_player_id)
        @game.update_attributes(current_status: "active")
        redirect_to game_path(@game)
    end
    
    def show
        #puts "BEFORE GAME"
        @game = current_game
        #puts "BEFORE PIECES"
        @pieces = current_game.pieces.order(:y_position).order(:x_position).to_a
        #puts "BEFORE KINGS"
        kings = current_game.pieces.where(piece_type: "King") 

        #puts "BEFORE LOOP"

        kings.each do |k| 

            if k.check?
                
                flash.now[:notice] = k.color.capitalize + ' King in Check'
                
            else
                #puts "----- NOT IN CHECK -----"
            end

            # elsif @king.stalemate? 
            #     puts "----- STALEMATE -----"
            #     @king.update_attributes(status: 'Stalemate')
            #     flash.alert 'Stalemate'
            #     # Set game status and result (?)
                
            #     #return
            # end   
        end 

    end
    
    def move
        @game = Game.find_by_id(params[:game_id])
        @pieces = @game.pieces
        @piece = Piece.find_by_id(params[:piece_id])
        @current_user = current_user.id
        if @game.turn_player_id == @current_user
            firebase_url    = 'https://fir-chess-270721.firebaseio.com/';
            firebase_secret = '8g8o1V0UsNy7O1I4kcRXlClM8vo4V4Yi44pQOLqt';
            firebase = Firebase::Client.new(firebase_url, firebase_secret)

            puts "firebase is #{firebase}"

            path = "games/" + @game.firebase_id
    
            @x_position = params[:x_position]
            @y_position = params[:y_position]
            @piece.move_to!(@x_position,@y_position)

            if @piece.piece_type == "Pawn" && @piece.pawn_promotion?
                redirect_to promote_path()
                return
            end

            puts "Before firebase"

            refreshVal = firebase.get(path + "/refresh")

            if refreshVal.body == true
                puts "Firebase set to false"
                response = firebase.update(path, {
                    :refresh => false
                })
            else
                puts "Firebase set to true"
                response = firebase.update(path, {
                    :refresh => true
                  })
            end
            
            else 
                #flash.now[:notice] = "Not yet your turn!"
                puts "nope"
            end
            puts "end"
            #redirect_to game_path(@game)

            respond_to do |format|
                format.js
            end
        end

    def forfeit
        @game = Game.find_by_id(params[:game_id])
        @game.update_attributes(loser_player_id: current_user.id)
        if @game.loser_player_id == @game.white_player_id
            @game.winner_player_id = @game.black_player_id
        else
            @game.winner_player_id = @game.white_player_id
        end
        @game.update_attributes(current_status: "inactive")
        redirect_to root_path
    end

    def promote
        @game = Game.find_by_id(params[:game_id])
        @piece_id = params[:piece_id]
        @white = @game.pieces.find_by(id: @piece_id).white
        @x = params[:x_position]
        @y = params[:y_position]
    end

    def promoted
        @game = Game.find_by_id(params[:game_id])
        @old_id = params[:old_id]
        @new_id = params[:new_id]
        @x = params[:x_position]
        @y = params[:y_position]

        old_piece = @game.pieces.find_by_id(@old_id)
        old_piece.update_attributes(x_position: nil, y_position: nil)

        new_piece = @game.pieces.find_by_id(@new_id)
        new_piece.update_attributes(x_position: @x, y_position: @y, captured: false)

        redirect_to game_path(@game)
    end

    def load_board
        @game = Game.find_by_id(params[:game_id])

        respond_to do |format|
            format.js
        end
    end
   
    def load_display
        @game = Game.find_by_id(params[:game_id])

        respond_to do |format|
            format.js
        end
    end

    private
    
    def game_params
        params.require(:game).permit(:name, :email)
    end

    def current_game
      @game ||= Game.find(params[:id])
    end
end

app/helpers/games_helper.rb
# frozen_string_literal: true

module GamesHelper
end

app/views/games/_board.html.erb
<% for j in 1..8 %>
    <% for i in 1..8 do %>
        <% if j % 2 == 1 %>
            <% if i % 2 == 1 %>
                <div id="<%= i.to_s + j.to_s %>" class = "square whiteSquare droppable">
            <% else %>
                <div id="<%= i.to_s + j.to_s %>" class = "square brownSquare droppable">
            <% end %>
        <% else %>
            <% if i % 2 == 1 %>
                <div id="<%= i.to_s + j.to_s %>" class="square brownSquare droppable">
            <% else %>
                <div id="<%= i.to_s + j.to_s %>" class="square whiteSquare droppable">
            <% end %>
        <% end %>
        <% if @game.contains_piece?(i, j) %>
            <%= image_tag(@game.pieces.find_by(x_position: i, y_position: j).name + ".png", 
                :class => "draggable", :id => @game.pieces.find_by(x_position: i, y_position: j).id) %>
        <% end %>
        </div>
    <% end %>
<% end %>

app/views/games/_display.html.erb

<div class="booyah-box-brown col-10 offset-1">
    <h2 style="text-align:center">
    <% flash.each do |type, msg| %>
            <%= msg %>
    <% end %>
    </h2>
    <p style="text-align:center"><h2 style="color:black;">Game Name: </h2><h2><%= @game.name %><h4></p>
    <p style="text-align:center"><h2 style="color:black;">Logged In User: </h2><h5><%= User.find_by_id(current_user.id).email %></h5></p>
    <% if current_user.id == @game.turn_player_id %>
        <p style="text-align:center"><h2 style="color:black">Your move</h2></p>
    <% else %>
        <p style="text-align:center"><h2 style="color:black">Not your move</h2></p>
    <% end %>
    <p style="text-align:center"><h2 style="color:black;">Black Player: </h2><h5><%= User.find_by_id(@game.black_player_id).email %></h5></p>

    <% if @game.black_player_id == @game.turn_player_id %>
        <p style="text-align:center"><h2 style="color:black">Black's turn to move</h2></p>
    <% end %>

    <% if current_user.id == @game.turn_player_id %>
        <%= simple_form_for @game, :url => game_forfeit_path(@game.id) do |f| %>
            <p style="text-align:center"><%= f.submit 'Forfeit', class: 'btn btn-danger' %></p>
        <% end %>
    <% end %>
    <p style="text-align:center"><h2 style="color:white;">White Player: </h2><h5><%= User.find_by_id(@game.white_player_id).email %></h5></p>
    <% if @game.white_player_id == @game.turn_player_id %>
        <p style="text-align:center"><h2 style="color:white">White's turn to move</h2></p>
    <% end %>
    <p style="text-align:center"><h2><a href="/">Return to Menu</a></h2></p>
</div>

app/views/games/index.html.erb
<div class="background">
  <br />
  
    <% @games.each do |game| %>
      <div class="booyah-box col-10 offset-1">
        <h1><%= game.name %></h1>

        <% if game.user.present? %>
          <small><%= game.user.email %></small>
        <% end %>
     </div>
    <% end %>

 <br />
</div>

app/views/games/load_board.js.erb
$('#brd').html("<%= j(render "board", locals: {:game => @game}) %>");
init_draggables_and_droppables();
$.ajax({
        type: "GET",
        url: "<%= @game.id %>/load_display",
        success: function(){
        console.log("in move.js.erb: display refresh success"); 
        }
    });

app/views/games/load_display.js.erb
$('#left-column').fadeOut().html("<%= j(render "display", locals: {:game => @game}) %>").fadeIn(1000);

app/views/games/move.js.erb
$('#brd').html("<%= j(render "board", locals: {:game => @game}) %>");
init_draggables_and_droppables();

app/views/games/new.html.erb
<div class="background">
  <br />
    <h1>Enter Your Game Details</h1>
    <%= simple_form_for @game do |f| %>
      <%= f.input :name %>
      <br />
      <%= f.submit 'Create', class: 'btn btn-danger' %>
    <% end %>

   <br />
</div>

app/views/games/promote.html.erb
<!-- Need to pass in the game and the x/y coordinates of the square on the first or last row -->

<% if @game.pieces.where(captured: true, white: @white).where.not(piece_type: "Pawn") != nil %>

<p style="text-align:center"><b>Select a new piece:</p>

<div class="container">
  <select onchange="getSelect(this)">
    <option value="">Select a piece:</option>
   <% @game.pieces.where(captured: true, white: @white).where.not(piece_type: "Pawn").each do |image| %>
   <option value=<%= image.id %>><%= image.piece_type %></option>
   <% end %>
   </select>
 </div>

 <% else %>

<p style="text-align:center"><b>No pieces available for pawn promotion</p>

 <% end %>

<%= form_tag "#", :id => 'promoted'%>

 <script>

 function getSelect(selectObject) {
  var value = selectObject.value;  
  console.log(value);
  var target_x = <%= @x %>;
    var target_y = <%= @y %>;
    var piece_id = value;
    var path = "/games/<%= @game.id.to_s %>/promoted/" + "<%= @piece_id %>" + "/" + piece_id + "/" + target_x + "/" + target_y;
    var $form =  $('#promoted');
    $form.attr('action', path); 
    console.log(path);
    $form.submit(); 
}

 </script> 

app/views/games/show.html.erb
<div class="background">
   <div class="flex-container">
      <div class="column" id="left-column">
        <%= render "display", locals: {:game => @game} %>
        </div>
   
        <div class="container" id="brd">
        <%= render "board", locals: {:game => @game} %>
        </div>

        <div class="column">
        <%= render_chat %>
      </div>
    </div>
    <br />
    

 <br />
</div>

<%= form_tag "#", :id => 'move'%>

<script src="https://cdn.firebase.com/js/client/1.0.18/firebase.js"></script>

<!-- The core Firebase JS SDK is always required and must be listed first -->
<script src="https://www.gstatic.com/firebasejs/7.11.0/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/7.6.1/firebase-auth.js"></script>
<script src="https://www.gstatic.com/firebasejs/7.6.1/firebase-database.js"></script>

<script>

    function init_draggables_and_droppables() {

        $(".draggable").draggable({ revert: 'invalid' });
        $(".droppable").droppable({
            drop: function( event, ui ) {

                var drop_target_id = event.target.id;
                var target_x = drop_target_id[0];
                var target_y = drop_target_id[1];
                var piece_id = ui.draggable.prop('id');
                var path = "/games/<%= @game.id.to_s %>/" + piece_id + "/" + target_x + "/" + target_y;
                console.log(path);
                var data = $("#move").serializeArray();//serialize form inputs
                console.log("ajax drop: board refresh success");

                $.ajax({
                    data: data,
                    type: "POST",
                    url: path,
                    success: function(){
                    console.log("NEVER REACHES: inside drop: board refresh success"); 
                    }
                });
       
            }     
        });

    }

    jQuery(function($) {
        init_draggables_and_droppables();
    
        //Your web app's Firebase configuration
        var firebaseConfig = {
            apiKey: "AIzaSyCa0OdzNtqg2CRUQibJT8ZxYjocMs8M3lQ",
            authDomain: "fir-chess-270721.firebaseapp.com",
            databaseURL: "https://fir-chess-270721.firebaseio.com",
            projectId: "firebase-chess-270721",
            storageBucket: "firebase-chess-270721.appspot.com",
            messagingSenderId: "883177546382",
            appId: "1:883177546382:web:60cc4e9cb5d519c386dfdf",
            measurementId: "G-WWMKRY87V7"
        };
        //Initialize Firebase
        firebase.initializeApp(firebaseConfig);

        var gamesRef = firebase.database().ref('games/' + '<%= @game.firebase_id %>');

        gamesRef.on('child_changed', function(snapshot) {

            $.ajax({
                    type: "GET",
                    url: "<%= @game.id %>/load_board",
                    success: function(){
                    console.log("child changed: load board refresh success"); 
                    }
                });

        }, function(error) {
            console.error(error);
        });

    });
</script>